enclave:
  spid:         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  iasSecretKey: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  iasHost:      https://api.trustedservices.intel.com/sgx/dev
  acceptGroupOutOfDate: false
  instances:
   - mrenclave: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
     debug:     true

signal:
  userToken:    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  serverToken:  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

redis:
  masterName:   mysentinel
  sentinelUrls:
   - 127.0.0.1:26379

directory:
  initialSize: 10000000
  minLoadFactor: 0.75
  maxLoadFactor: 0.85
  sqs:
    accessKey: asdf
    accessSecret: asdf
    queueUrl: asdf
    queueRegion: ap-southeast-1

limits:
  contactQueries:
    bucketSize:        50000
    leakRatePerMinute: 50000
  remoteAttestations:
    bucketSize:        50000
    leakRatePerMinute: 50000
